---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: springdemo
  namespace: flux-system
spec:
  secretRef:
    name: regcred
  image: smarsh-docker-snapshot-local.jfrog.io/gosmtp
  interval: 1m0s
